version: "3.8"

services:
  config:
    build: ./config
    container_name: config
    ports:
      - "8888:8888"
    restart: unless-stopped

  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    depends_on:
      - config
    environment:
      - CONFIG_URI=http://config:8888
    ports:
      - "8761:8761"
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - config
      - service-discovery
    environment:
      - CONFIG_URI=http://config:8888
    ports:
      - "9000:8080"
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak:15.0.2
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_IMPORT=/keycloak/bloggingnetwork-realm.json
    volumes:
      - ./keycloak/bloggingnetwork-realm.json:/keycloak/bloggingnetwork-realm.json
    ports:
      - "8080:8080"
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - CONFIG_URI=http://config:8888
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    depends_on:
      - config
      - keycloak
      - redis
      - rabbitmq
    restart: unless-stopped

  post-service:
    build: ./post-service
    container_name: post-service
    environment:
      - CONFIG_URI=http://config:8888
      - CLIENT_ID=post-service
      - CLIENT_SECRET=14feda15-2dff-4b5e-83c1-e822c45f896d
      - POSTGRES_URL=jdbc:postgresql://post-service-db:5432/post_service
      - POSTGRES_USER=${POST_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${POST_SERVICE_DB_PASSWORD}
    depends_on:
      - config
      - keycloak
      - rabbitmq
    restart: unless-stopped

  post-service-db:
    image: postgres
    container_name: post-service-db
    environment:
      - POSTGRES_DB=post_service
      - POSTGRES_USER=${POST_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${POST_SERVICE_DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"

  user-feed-service:
    build: ./user-feed-service
    container_name: user-feed-service
    environment:
      - CONFIG_URI=http://config:8888
      - CLIENT_ID=user-feed-service
      - CLIENT_SECRET=533f8bc6-3da6-4904-863e-11c7c56c8aa3
      - POSTGRES_URL=jdbc:postgresql://user-feed-db:5432/user_feed
      - POSTGRES_USER=${USER_FEED_DB_USER}
      - POSTGRES_PASSWORD=${USER_FEED_DB_PASSWORD}
    depends_on:
      - config
      - user-feed-db
      - keycloak
      - rabbitmq
      - service-discovery
    restart: unless-stopped

  user-feed-db:
    image: postgres
    container_name: user-feed-db
    environment:
      - POSTGRES_DB=user_feed
      - POSTGRES_USER=${USER_FEED_DB_USER}
      - POSTGRES_PASSWORD=${USER_FEED_DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"
