version: "3.8"

services:
  config:
    build: ./config
    container_name: config
    ports:
      - "8888:8888"
    restart: unless-stopped

  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    depends_on:
      - config
    environment:
      - CONFIG_URI=http://config:8888
    ports:
      - "8761:8761"
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - config
      - service-discovery
    environment:
      - CONFIG_URI=http://config:8888
    ports:
      - "9000:8080"
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak:15.0.2
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - CONFIG_URI=http://config:8888
    depends_on:
      - config
      - keycloak
      - redis
      - rabbitmq
    restart: unless-stopped

  post-service:
    build: ./post-service
    container_name: post-service
    environment:
      - CONFIG_URI=http://config:8888
    depends_on:
      - config
      - keycloak
      - rabbitmq
    restart: unless-stopped

  user-feed-service:
    build: ./user-feed-service
    container_name: user-feed-service
    environment:
      - CONFIG_URI=http://config:8888
    depends_on:
      - config
      - keycloak
      - rabbitmq
    restart: unless-stopped
