version: "3.8"

services:
  config:
    build: ./config
    container_name: config
    ports:
      - "8888:8888"
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak:15.0.2
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config:8888
    depends_on:
      - config
      - keycloak
    ports:
      - "8090:8080"
    restart: unless-stopped
