spring:
  application:
    name: service-discovery
  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8888}

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false