spring:
  redis:
    host: redis
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

app:
  keycloak:
    serverUrl: http://keycloak:8080/auth
    realm: master