spring:
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/master

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

app:
  keycloak:
    serverUrl: http://keycloak:8080/auth
    realm: master

  messaging:
    users:
      topic-exchange: users
      follow-routing-key: user.follow
      unfollow-routing-key: user.unfollow
      following-event-queue: following-event-queue
    posts:
      topicExchange: posts
      post-created-routing-key: post.created
      post-deleted-routingKey: post.deleted
      post-event-queue: post-event-queue