spring:
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  redis:
    host: redis
    port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            authorization-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}/protocol/openid-connect/authorize
            token-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

app:
  keycloak:
    serverUrl: http://keycloak:8080/auth
    realm: bloggingnetwork