spring:
  cache:
    users:
      cache-name: userCache
      time-to-live: 60

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    com.mikhailkarpov.bloggingnetwork.posts.client.UserServiceClient: DEBUG