spring:
  cloud:
    stream:
      bindings:
        postEvents-out-0:
          destination: posts
      rabbit:
        binder:
          connection-name-prefix: ${spring.application.name}
  cache:
    prefix: post-service
    expirations:
      users: 60
  datasource:
    url: jdbc:postgresql://postgres:5432/post_service
    username: post_service
    password: post_service

CLIENT_ID: post-service
CLIENT_SECRET: 9ac2c424-117b-4f69-b853-24c7f2661535
